### ISSUE TITLE
JIT assembler function missing for aarch64

### ISSUE THREAD

**Issue by Danliran** [fujitsu/dnnl_aarch64#11]
Hi, *

MKL-DNN  use jit_* function to produce assembler code, but it seems this repo didn`t produce arm assembler base on Xbyak_aarch64. If i am wrong,which interface can do it.

**Comment by kawakami-k** [comment]
Hi, Danliran-san
`tag:v0_9_0_base_0.19_first_public_release` supports JIT code generation only for `jit_uni_reorder.cpp`.

This weekend or next week, we will update this repository, which supports, compared to the current version, wide range of parameters and processing, such as convolution, eltwise, bach_norm, pooling. This version, based on DNNL v0.21.2, still has limitation that supported data precision is only float32. Please wait a few days. 

We would like to improve the quality of our forked source code with a wide range of parameters, processing kernels, data precision. Thank you.

**Comment by Danliran** [comment]
good news! Iconfuse about to generate arm assembler code, do you have any reference doc about xbyak_aarch64 to generate it.
thanks in advance!

some questions like:

how to prepare the register?
how to generate add(w0, w1)  to (add, w0, w1, w0)?

**Comment by kawakami-k** [comment]
Sorry for lack of documents.
Here is some explanations.
https://github.com/fujitsu/xbyak_aarch64/blob/master/README.md

Xbyak_aarch64 has almost the same conecpt of Xbyak so that Xbyak's samples may be useful.
https://github.com/herumi/xbyak/

We have a another good news.
We released xbyak_translator_aarch64 today.
https://github.com/fujitsu/xbyak_translator_aarch64
It is used by the newer version of dnnl_aarch64, available .
